### ISSUE TITLE
the retrieval performance worse than classification performance

### ISSUE THREAD

**Issue by iWeisskohl** [kevinlin311tw/Caffe-DeepBinaryCode#21]
hi,Kevin, I have a question that why the retrieval map is lower than classification accuracy in imagenet dataset, but is can stay the same in mnist or cifar dataset?  For my own model, it reduces about 20%, and there is no problem with mean data. Have you ever meet the similar problem or could you please give me some suggestion? thank you so much!

**Comment by kevinlin311tw** [comment]
Yes. I also noticed this issue especially when testing on fine-grained datasets as well as ILSVRC12. Perhaps softmax loss is only good for classification, and it may not well separate the features which are extracted from visually similar images. 
In other point of views, image retrieval is doing exact feature matching. We need to compare and match the global distribution of the feature vectors. In contrast, classification is relatively easy since it only takes care the top1/top5 activated neurons. That is, retrieval is more challenging then classification especially for fine-grained task.

**Comment by iWeisskohl** [comment]
thank you for your nice explanation! I learned a lot from your paper,you did a very good job in image retrieval field.
