### ISSUE TITLE
How can I get the path ./matlab/caffe/matcaffe_batch_feat.m?

### ISSUE THREAD

**Issue by fanwenyuan** [kevinlin311tw/Caffe-DeepBinaryCode#25]
I met the 10% map error when testing the demo on cigar-10,when I was following the issue https://github.com/kevinlin311tw/caffe-cvprw15/issues/17 I can't find that file.So where is it? There is only a +caffe file under my ./matlab and I can't find that file in it.

**Comment by kevinlin311tw** [comment]
Please try the file `feat_batch.m`

**Comment by fanwenyuan** [comment]
@kevinlin311tw Thanks.So I just need to modify that file as the FAQ referred? How can I get the KevinNet_cifar10 model and its prorotxt?

**Comment by kevinlin311tw** [comment]
The reason you got 10% mAP is that Matlab does not load the mean file correctly. Directly specifying the path of the mean file solves this problem.

For this SSDH repo, you have to use SSDH model instead of KevinNet_cifar10 model. The KevinNet_cifar10 model is for another repo. You should already downloaded the SSDH model and the corresponding prototxt if you follow the instruction.

**Comment by fanwenyuan** [comment]
@kevinlin311tw I have specified the mean file and rebuilt the project, but still get 0.1 map.

**Comment by kevinlin311tw** [comment]
Please also check the path of the image files. Mack sure that Matlab can read the images successfully...

**Comment by fanwenyuan** [comment]
Thanks. The problem has solved. After specify the path, I deleted the binary-train.mat and binary-test.mat under /analysis and reproduce them. Or the code will load the error ones directly and skip the feat_batch.m. Hope it can be helpful.
