### ISSUE TITLE
About the model used on SUN397 dataset

### ISSUE THREAD

**Issue by fanwenyuan** [kevinlin311tw/Caffe-DeepBinaryCode#26]
Excuse me, when I was trying to train my own model on Sun397 but failed. Did you use a pre-trained model with another dataset?

**Comment by kevinlin311tw** [comment]
Thanks for your interest in this work. As I can recall, we didn't train the model from scratch. Training from scratch may need additional tricks, and it is not the major scope of this work.

Instead, we trained the model using pre-trained weights from ILSVRC12. This leads to good performance. In addition, we empirically found that training the model using pre-trained weights from Places dataset leads to higher accuracy. I think this is mainly because Places datasets consists of scene images, where should better fit to the image categories in SUN397.
