### ISSUE TITLE
Confuse about the figure

### ISSUE THREAD

**Issue by sunyinhui** [kevinlin311tw/Caffe-DeepBinaryCode#3]
What is the number of red dot in the last layer???
the number of green dot is one??? or not ??
what is the meaning of that??? Thanks very much!!!
![numbers](https://cloud.githubusercontent.com/assets/6357309/13840712/1736764a-ec5f-11e5-837b-a6596a08b0d4.jpg)

**Comment by sunyinhui** [comment]
![image](https://cloud.githubusercontent.com/assets/6357309/13846869/11d68c1e-ec85-11e5-9ef1-3705c65537ba.png)
I can get the message. please help me

**Comment by kevinlin311tw** [comment]
Hi @sunyinhui 
Sorry. Since this project is a work in progress, some parameter names may confuse. We will improve this as soon as possible.

The red and green parts represent two different objective functions. They are not layers, so they don't have "nodes". 
The green one represents the `K1_EuclideanLoss`, and the red one is `K2_EuclideanLoss`.
`K1_EuclideanLoss` will enforce each node in `encode_neuron` to be 0 or 1.
`K2_EuclideanLoss` will ensure each node in `encode_neuron` has a 50% chance of being 0 or 1.

Btw, our binary codes are learn in the `encode_neuron`. During testing, we extract the binary codes from `encode_neuron`

Should you have any question about the paper, please feel free to email me.

**Comment by sunyinhui** [comment]
Oh , Thanks!  ^_^

**Comment by sunyinhui** [comment]
Hi Kevinlin，I can not underdtand deeply the loss_beta and loss_gamma . Please help me. Thanks
